#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
segmentation_tsam.py
====================
Intra-day segmentation of the typical days (TD) generated by the ESMC toolchain.
Produces the data used by ESMC_model_AMPL_pathway_SEG.mod:

  * t_op[s,td]        duration (h) of segment s in typical day td (sum over s = 24)
  * EUD series        per segment (electricity/heating/cooling/mobility) -> SUM
  * c_p_t             per segment (WIND/PV/HYDRO/TIDAL/SOLAR ...)        -> MEAN
  * T_H_TD            365*n_seg tuples

Design:
  - tsam only sets the segment BOUNDARIES (hierarchical clustering of adjacent
    hours over all columns). Existing k-medoid TDs are kept via predefClusterOrder.
  - Segment VALUES are computed here with the right convention per series,
    not with tsam's rescaling.

Conventions:
  - EUD: the model uses ts/t_op as power, so ts_seg = SUM of the segment hours.
  - c_p_t: the model uses F*c_p_t (already hourly), so c_p_t_seg = MEAN of the hours.
  - Both reduce to identity with n_seg = 24.

Pure functions (no tsam needed) have a self-test (from the repository root):
    python -m esmc.preprocessing.segmentation_tsam

Author: Pablo Jimenez Zabalaga
"""

import logging
import numpy as np
import pandas as pd

# Demand series (SUM convention). All other series in ts_td -> MEAN.
DEFAULT_EUD_SERIES = {
    'ELECTRICITY', 'HEAT_LOW_T_SH', 'SPACE_COOLING',
    'MOBILITY_PASSENGER', 'MOBILITY_FREIGHT',
}

# Column weights used by tsam to place segment boundaries.
# Prioritizes the electricity balance (demand + VRE). Unlisted series get weight 1.0.
# Set to None to use equal weights.
ELEC_BALANCE_WEIGHTS = {
    'ELECTRICITY':   3.0,
    'PV':            3.0,
    'WIND_ONSHORE':  3.0,
    'HYDRO_RIVER':   3.0,
    #'WIND_OFFSHORE': 0.0,
    #'TIDAL':       0.0,
    #'HYDRO_DAM': 0.0,
}


# ===========================================================================
# 1. PURE CORE (no tsam)
# ===========================================================================

def bounds_from_durations(durations):
    """0-based [start, end) bounds of each segment from its durations (cumsum)."""
    bounds, start = [], 0
    for d in durations:
        d = int(round(d))
        bounds.append((start, start + d))
        start += d
    return bounds


def aggregate_profile(profile_24, durations, how):
    """Aggregate a 24 h profile into segments.

    how: 'sum' (EUD), 'mean' (c_p_t), 'max' or 'min' (bounds).
    """
    profile_24 = np.asarray(profile_24, dtype=float)
    if profile_24.shape[0] != int(sum(durations)):
        raise ValueError(f"Profile has {profile_24.shape[0]} h but durations sum to "
                         f"{int(sum(durations))} (must be 24).")
    out = []
    for (a, b) in bounds_from_durations(durations):
        block = profile_24[a:b]
        if how == 'sum':
            out.append(block.sum())
        elif how == 'mean':
            out.append(block.mean())
        elif how == 'max':          # lower bounds (e.g. state_of_charge_ev)
            out.append(block.max())
        elif how == 'min':
            out.append(block.min())
        else:
            raise ValueError(f"Unknown how: {how!r} (use sum|mean|max|min)")
    return np.array(out)


def segment_ts_td(ts_td, durations_per_td, eud_series=DEFAULT_EUD_SERIES):
    """Segment the ts_td of ONE region.

    ts_td : DataFrame, MultiIndex (series, hour 1..24) x TD_number columns.
    durations_per_td : dict {TD_number -> list of durations (sum = 24)}.
    Returns the segmented ts_td: MultiIndex (series, 1..n_seg) x TD_number.
    """
    series_names = list(dict.fromkeys(ts_td.index.get_level_values(0)))
    td_numbers = list(ts_td.columns)
    data = {}  # (series, seg) -> {td: val}
    for s in series_names:
        how = 'sum' if s in eud_series else 'mean'
        sub = ts_td.loc[(s, slice(None)), :].droplevel(0)  # rows = hour, cols = TD
        sub = sub.sort_index()                              # hour order
        for td in td_numbers:
            profile = sub[td].to_numpy()
            seg_vals = aggregate_profile(profile, durations_per_td[td], how)
            for k, v in enumerate(seg_vals, start=1):
                data.setdefault((s, k), {})[td] = v
    idx = pd.MultiIndex.from_tuples(sorted(data.keys()), names=ts_td.index.names)
    out = pd.DataFrame(index=idx, columns=td_numbers, dtype=float)
    for (s, k), dvals in data.items():
        for td, v in dvals.items():
            out.loc[(s, k), td] = v
    return out


def make_t_op_df(durations_per_td, n_seg):
    """t_op DataFrame: rows = segment 1..n_seg, columns = TD_number (AMPL 'param t_op')."""
    td_numbers = sorted(durations_per_td.keys())
    df = pd.DataFrame(index=np.arange(1, n_seg + 1), columns=td_numbers, dtype=float)
    df.index.name = 'SEGMENT'
    for td in td_numbers:
        durs = list(durations_per_td[td])
        if len(durs) != n_seg:
            raise ValueError(f"TD {td}: {len(durs)} segments, expected {n_seg}.")
        if int(round(sum(durs))) != 24:
            raise ValueError(f"TD {td}: durations sum to {sum(durs)} (must be 24).")
        df[td] = [float(int(round(d))) for d in durs]
    return df


def build_segmented_t_h_td(td_of_days, n_seg):
    """Build T_H_TD for PERIODS = 365*n_seg (one per segment per calendar day).

    td_of_days : array (len 365) with the TD_number of each day (1-based).
    Returns DataFrame [H_of_Y, H_of_D, TD_number]:
      H_of_Y = 1..365*n_seg, H_of_D = 1..n_seg, TD_number = TD of the day.
    """
    td_of_days = np.asarray(td_of_days).astype(int)
    n_days = len(td_of_days)
    th = pd.DataFrame({
        'H_of_Y': np.arange(1, n_days * n_seg + 1),
        'H_of_D': np.resize(np.arange(1, n_seg + 1), n_days * n_seg),
        'TD_number': np.repeat(td_of_days, n_seg),
    })
    return th


def t_end_from_t_op(t_op_df):
    """t_end[s,td] = cumulative hours at the END of segment s (validation only)."""
    return t_op_df.cumsum(axis=0)


def recompute_peak_factor(full_year_series, ts_td_seg_series):
    """Peak factor = yearly max / max over segmented TDs.

    ts_td_seg_series must already be POWER per segment (value / t_op).
    """
    max_yr = float(np.nanmax(full_year_series))
    max_td = float(np.nanmax(ts_td_seg_series))
    if max_td <= 0:
        return np.nan
    return max_yr / max_td


def build_state_of_charge_ev_3d(ev_24_by_tech, durations_per_td, n_seg):
    """3D state_of_charge_ev: {tech -> DataFrame(index=1..n_seg, cols=TD_number)}.

    ev_24_by_tech : dict {tech -> 24 hourly values} (minimum SOC per clock hour).
    Uses MAX per segment, since state_of_charge_ev is a lower bound.
    With n_seg = 24 the hourly pattern is copied to every TD.
    """
    td_numbers = sorted(durations_per_td.keys())
    out = {}
    for tech, prof in ev_24_by_tech.items():
        prof = np.asarray(prof, dtype=float)
        df = pd.DataFrame(index=np.arange(1, n_seg + 1), columns=td_numbers, dtype=float)
        df.index.name = 'SEGMENT'
        for td in td_numbers:
            df[td] = aggregate_profile(prof, durations_per_td[td], how='max')
        out[tech] = df
    return out


# ===========================================================================
# 2. TSAM CALL (boundaries/durations only) -- requires tsam
# ===========================================================================

def tsam_segment_durations(ts_td_by_region, n_seg, nbr_td,
                           cluster_method='hierarchical', solver='highs',
                           col_weights=None):
    """Return {TD_number -> list of durations (sum = 24)} using tsam.

    ts_td_by_region : dict {region -> ts_td}.
    All regions and series are clustered together, so every region shares the
    same segmentation (t_op is not indexed by region in the .mod).
    Existing TDs are kept via predefClusterOrder.

    col_weights : optional {series -> weight} for the tsam distance
        (unlisted series -> 1.0; None -> equal weights). See ELEC_BALANCE_WEIGHTS.
    """
    import tsam.timeseriesaggregation as tsam

    td_numbers = sorted(next(iter(ts_td_by_region.values())).columns)
    if len(td_numbers) != nbr_td:
        logging.warning(f"[tsam] nbr_td={nbr_td} but ts_td has {len(td_numbers)} TDs")

    # Joint frame: rows = TD x 24 hours, columns = (region, series)
    blocks = []
    weight_dict = {}
    for region, ts_td in ts_td_by_region.items():
        series_names = list(dict.fromkeys(ts_td.index.get_level_values(0)))
        for s in series_names:
            sub = ts_td.loc[(s, slice(None)), :].droplevel(0).sort_index()  # hour x TD
            # stack TDs one after another (24 values each)
            col = np.concatenate([sub[td].to_numpy() for td in td_numbers])
            name = f"{region}|{s}"
            blocks.append(pd.Series(col, name=name))
            weight_dict[name] = float(col_weights.get(s, 1.0)) if col_weights else 1.0
    raw = pd.concat(blocks, axis=1)
    # synthetic hourly index (tsam only uses it to split into 24 h periods)
    raw.index = pd.date_range('2020-01-01', periods=len(raw), freq='h')

    predef = list(range(len(td_numbers)))  # one period per TD, in order

    agg = tsam.TimeSeriesAggregation(
        raw,
        noTypicalPeriods=len(td_numbers),
        hoursPerPeriod=24,
        noSegments=int(n_seg),
        segmentation=True,
        clusterMethod=cluster_method,
        predefClusterOrder=predef,
        rescaleClusterPeriods=False,   # values are not taken from tsam
        solver=solver,
        weightDict=(weight_dict if col_weights else {}),
    )
    agg.createTypicalPeriods()
    if col_weights:
        logging.info(f"[tsam] Column weights: {dict(col_weights)}")

    durations_per_td = _extract_durations(agg, td_numbers, n_seg)

    # each TD must sum to 24
    for td, durs in durations_per_td.items():
        if int(round(sum(durs))) != 24:
            raise RuntimeError(f"[tsam] TD {td}: durations {durs} do not sum to 24. "
                               "Check the tsam version/output.")
    logging.info(f"[tsam] Segmentation OK: {n_seg} segments/TD, {len(durations_per_td)} TDs")
    return durations_per_td


def _extract_durations(agg, td_numbers, n_seg):
    """Extract per-period durations from the tsam object.
    period_idx i (0-based, predefClusterOrder order) -> TD_number td_numbers[i].
    """
    durations_per_td = {}
    sdd = getattr(agg, 'segmentDurationDict', None)

    # 1. Try segmentDurationDict
    if sdd is not None and len(sdd) >= len(td_numbers):
        try:
            for i, td in enumerate(td_numbers):
                entry = sdd[i] if i in sdd else sdd[list(sdd.keys())[i]]
                durations_per_td[td] = _as_duration_list(entry, n_seg)
            return durations_per_td
        except (IndexError, KeyError, AttributeError):
            pass

    # 2. Fallback: 'Segment Duration' index level of typicalPeriods
    typ = agg.typicalPeriods if hasattr(agg, 'typicalPeriods') else agg.createTypicalPeriods()
    lvl = 'Segment Duration'
    if isinstance(typ.index, pd.MultiIndex) and lvl in (typ.index.names or []):
        per_lvl = typ.index.names[0]
        for i, td in enumerate(td_numbers):
            durs = typ.xs(i, level=per_lvl).index.get_level_values(lvl).tolist()
            durations_per_td[td] = [int(round(x)) for x in durs]
        return durations_per_td

    raise RuntimeError("Could not extract durations from tsam (no segmentDurationDict "
                       "and no 'Segment Duration' index). Check the tsam version.")


def _as_duration_list(entry, n_seg):
    """Convert a segmentDurationDict entry to a list of ints (len = n_seg)."""
    if isinstance(entry, dict):
        vals = [entry[k] for k in sorted(entry.keys())]
    else:
        vals = list(np.asarray(entry).ravel())
    return [int(round(x)) for x in vals]


# ===========================================================================
# 3. DATA VALIDATION (no AMPL) -- requires tsam and real data
# ===========================================================================

def validate_segmentation(ts_td_by_region, n_seg, nbr_td, eud_series=DEFAULT_EUD_SERIES,
                          rmse_tol=None):
    """Validate segmented data before running AMPL. Returns a results dict.

    Checks:
      (1) sum_s t_op[s,td] == 24 for every TD.
      (2) Identity with n_seg = 24: re-segmenting reproduces the original ts_td.
      (3) Reconstruction RMSE per series (informative; enforced if rmse_tol is set).
    """
    results = {'n_seg': n_seg, 'checks': {}}

    # (1) main segmentation
    durs = tsam_segment_durations(ts_td_by_region, n_seg, nbr_td)
    t_op = make_t_op_df(durs, n_seg)
    ok_sum = bool((t_op.sum(axis=0).round().astype(int) == 24).all())
    results['checks']['sum_t_op_eq_24'] = ok_sum
    results['t_op'] = t_op

    # (2) identity with n_seg = 24
    durs24 = tsam_segment_durations(ts_td_by_region, 24, nbr_td)
    ident_ok = all(int(round(sum(d))) == 24 and len(d) == 24 for d in durs24.values())
    max_abs = 0.0
    for region, ts_td in ts_td_by_region.items():
        seg24 = segment_ts_td(ts_td, durs24, eud_series)
        a = ts_td.sort_index()
        b = seg24.sort_index()
        b.index = a.index  # hour == segment
        max_abs = max(max_abs, float(np.nanmax(np.abs(a.to_numpy() - b.to_numpy()))))
    results['checks']['identity_nseg24'] = bool(ident_ok and max_abs < 1e-9)
    results['identity_max_abs_err'] = max_abs

    # (3) reconstruction RMSE for the requested n_seg
    rmse_by_series = {}
    for region, ts_td in ts_td_by_region.items():
        seg = segment_ts_td(ts_td, durs, eud_series)
        for s in dict.fromkeys(ts_td.index.get_level_values(0)):
            how = 'sum' if s in eud_series else 'mean'
            orig = ts_td.loc[(s, slice(None)), :].droplevel(0).sort_index()
            rec = np.zeros_like(orig.to_numpy(), dtype=float)
            for j, td in enumerate(orig.columns):
                for k, (a, b) in enumerate(bounds_from_durations(durs[td]), start=1):
                    val = seg.loc[(s, k), td]
                    # back to hours: EUD spread as val/dur, c_p_t repeated
                    rec[a:b, j] = (val / (b - a)) if how == 'sum' else val
            err = orig.to_numpy() - rec
            rmse_by_series[f"{region}|{s}"] = float(np.sqrt(np.nanmean(err ** 2)))
    results['rmse_by_series'] = rmse_by_series
    if rmse_tol is not None:
        results['checks']['rmse_below_tol'] = all(v <= rmse_tol for v in rmse_by_series.values())

    results['all_passed'] = all(results['checks'].values())
    return results


# ===========================================================================
# 4. SELF-TEST of the pure core (no tsam)
# ===========================================================================

def _selftest():
    print("== Self-test: pure core (no tsam) ==")
    rng = np.random.default_rng(1)
    nbr_td = 3
    hours = np.arange(1, 25)
    series = ['ELECTRICITY', 'HEAT_LOW_T_SH', 'WIND_ONSHORE', 'PV']  # 2 EUD + 2 res

    # synthetic ts_td for one region: MultiIndex (series, hour) x TD
    idx = pd.MultiIndex.from_product([series, hours], names=['ts', 'H_of_D'])
    ts_td = pd.DataFrame(rng.random((len(idx), nbr_td)) , index=idx,
                         columns=pd.Index([1, 2, 3], name='TD_number'))

    # --- n_seg = 24: 24 segments of 1 h ---
    durs24 = {td: [1] * 24 for td in [1, 2, 3]}
    seg24 = segment_ts_td(ts_td, durs24)
    b = seg24.sort_index(); a = ts_td.sort_index(); b.index = a.index
    err24 = float(np.nanmax(np.abs(a.to_numpy() - b.to_numpy())))
    print(f"  [n_seg=24] ts_td identity: max|err| = {err24:.2e}  -> "
          f"{'OK' if err24 < 1e-12 else 'FAIL'}")

    # --- n_seg = 4: 6 h segments. Check SUM vs MEAN ---
    durs4 = {td: [6, 6, 6, 6] for td in [1, 2, 3]}
    seg4 = segment_ts_td(ts_td, durs4)
    # EUD (ELECTRICITY): segment 1 = sum of hours 1..6
    elec_h = ts_td.loc[('ELECTRICITY', slice(None)), 1].droplevel(0).sort_index().to_numpy()
    exp_sum = elec_h[0:6].sum()
    got_sum = seg4.loc[('ELECTRICITY', 1), 1]
    print(f"  [n_seg=4] EUD seg1 = SUM(h1..6): expected {exp_sum:.6f} got {got_sum:.6f}  -> "
          f"{'OK' if abs(exp_sum - got_sum) < 1e-12 else 'FAIL'}")
    # c_p_t (WIND): segment 1 = mean of hours 1..6
    wind_h = ts_td.loc[('WIND_ONSHORE', slice(None)), 1].droplevel(0).sort_index().to_numpy()
    exp_mean = wind_h[0:6].mean()
    got_mean = seg4.loc[('WIND_ONSHORE', 1), 1]
    print(f"  [n_seg=4] c_p_t seg1 = MEAN(h1..6): expected {exp_mean:.6f} got {got_mean:.6f}  -> "
          f"{'OK' if abs(exp_mean - got_mean) < 1e-12 else 'FAIL'}")
    # EUD energy conservation: sum_s ts_seg = sum_h ts_td (per TD)
    cons = abs(seg4.loc[('ELECTRICITY', slice(None)), 1].sum() -
               ts_td.loc[('ELECTRICITY', slice(None)), 1].sum())
    print(f"  [n_seg=4] EUD conservation (sum_s == sum_h): |diff| = {cons:.2e}  -> "
          f"{'OK' if cons < 1e-12 else 'FAIL'}")

    # --- t_op and t_end ---
    t_op = make_t_op_df(durs4, 4)
    print(f"  t_op sums to 24/TD: {'OK' if (t_op.sum().round().astype(int) == 24).all() else 'FAIL'}")
    t_end = t_end_from_t_op(t_op)
    exp_tend = [6, 12, 18, 24]
    print(f"  t_end TD1 = {t_end[1].tolist()} (expected {exp_tend})  -> "
          f"{'OK' if t_end[1].tolist() == exp_tend else 'FAIL'}")
    t_end24 = t_end_from_t_op(make_t_op_df(durs24, 24))
    print(f"  t_end(n_seg=24) == 1..24: "
          f"{'OK' if t_end24[1].tolist() == list(range(1, 25)) else 'FAIL'}")

    # --- T_H_TD ---
    td_of_days = np.resize([1, 2, 3], 365)
    th24 = build_segmented_t_h_td(td_of_days, 24)
    th4 = build_segmented_t_h_td(td_of_days, 4)
    print(f"  T_H_TD n_seg=24: {len(th24)} rows (expected 8760)  -> "
          f"{'OK' if len(th24) == 8760 else 'FAIL'}")
    print(f"  T_H_TD n_seg=4 : {len(th4)} rows (expected {365*4})  -> "
          f"{'OK' if len(th4) == 365*4 else 'FAIL'}")
    print(f"  T_H_TD n_seg=4 H_of_D in 1..4: "
          f"{'OK' if set(th4['H_of_D'].unique()) == {1,2,3,4} else 'FAIL'}")

    # --- 3D state_of_charge_ev (MAX) ---
    # example pattern: 0.6 at hour 7, zero elsewhere
    ev = {'CAR_BEV': [0.0]*6 + [0.6] + [0.0]*17}
    # n_seg = 24: hour 7 -> 0.6 in every TD, 0 elsewhere
    ev24 = build_state_of_charge_ev_3d(ev, durs24, 24)['CAR_BEV']
    ok_bcast = (abs(ev24.loc[7, 1] - 0.6) < 1e-12 and
                abs(ev24.drop(index=7).to_numpy().max()) < 1e-12 and
                (ev24.loc[7] == 0.6).all())
    print(f"  [EV n_seg=24] hourly pattern copied (0.6 only in seg 7, all TDs): "
          f"{'OK' if ok_bcast else 'FAIL'}")
    # n_seg = 4: hour 7 falls in segment 2 (hours 7..12) -> MAX = 0.6
    ev4 = build_state_of_charge_ev_3d(ev, durs4, 4)['CAR_BEV']
    ok_max = (abs(ev4.loc[2, 1] - 0.6) < 1e-12 and
              abs(ev4.drop(index=2).to_numpy().max()) < 1e-12)
    print(f"  [EV n_seg=4] MAX keeps 0.6 in the segment containing hour 7: "
          f"{'OK' if ok_max else 'FAIL'}  (seg2={ev4.loc[2,1]:.2f})")

    print("== End of self-test ==")


if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO, format='%(levelname)s %(message)s')
    _selftest()
